name: OurOffice
favicon: null
layout_spectrum: 0.49007410323247313
typography_spectrum: 0.24209203734062612
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.6770677526947111
  lightness: 0.03948428831063211
  saturation: 0.506089128088206
  rhythmicContrast: 0.7617223002016544
purpose: []
